services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: catalog_api_prod
    command: node dist/shared/infra/http/server.js
    ports:
      - "3333:3333"
    env_file:
      - .env
    restart: always

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: catalog_worker_prod
    command: node dist/modules/products/workers/EnrichmentWorker.js
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: catalog_ui_prod
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
